### ISSUE TITLE
Error during instantiation of NgZone!

### ISSUE THREAD

**Issue by distravantari** [500tech/angular2-webpack-es6#5]
![screen shot 2016-06-12 at 8 43 19 pm](https://cloud.githubusercontent.com/assets/10736018/15991485/5a26943a-30de-11e6-8eb9-c6b5a72ccd1d.png)

whats wrong with this actually?
thank you.

**Comment by nxxcxx** [comment]
add this in _index.html_
`<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>`

remove this line in _bootstrap.js_
`import 'reflect-metadata';`

add these before calling bootstrap
`import { enableProdMode } from 'angular2/core';`
`enableProdMode();`

**Comment by borisd** [comment]
Hi, updated to latest version of Angular2
