### ISSUE TITLE
js file size after build

### ISSUE THREAD

**Issue by natiz** [500tech/angular2-webpack-es6#6]
How come the bundle.js size is 10MB?!

```
 Asset       Size  Chunks             Chunk Names
```

 bundle.js    10.7 MB       0  [emitted]  main
index.html  292 bytes          [emitted]
chunk    {0} bundle.js (main) 4.35 MB [rendered]

**Comment by borisd** [comment]
Hi

Fixed in https://github.com/500tech/angular2-webpack-es6/pull/7
